# Generated by Django 2.2 on 2021-04-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_remove_course_lesson_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('title', models.CharField(default='', max_length=100, verbose_name='作业标题')),
                ('deadline', models.DateField(default=django.utils.timezone.now, verbose_name='截止时间')),
                ('attach', models.FileField(blank=True, null=True, upload_to='homework/homeworktask/%Y/%m', verbose_name='附件')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': '作业任务',
                'verbose_name_plural': '作业任务',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('attach', models.FileField(blank=True, null=True, upload_to='homework/homeworkfile/%Y/%m', verbose_name='附件')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('comment', models.TextField(default='', verbose_name='教师评语')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.HomeworkTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
            },
        ),
    ]
