# Generated by Django 2.2 on 2021-04-13 21:02

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20210413_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='homeworktask',
            name='attach',
        ),
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='正文'),
        ),
    ]
